name: SiJohnsPhotografic
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1829787
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#423d1c'
    - '#857f4b'
    - '#ff0000'
    - '#ffffff'
    - '#00c999'
  brandStrength: 0.5
  lightness: 0.9021277
  saturation: 0.5893617
  rhythmicContrast: 0.612766
purpose: []
